version: '3.8'

services:
  app:
    image: ggi-web:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "3000"

  nginx:
    image: nginx:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app