export default function DataDetailPage() {
  return (
    <>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
      <div>디테일 페이지</div>
    </>
  )
}
