import { atom } from 'recoil'

export const stepState = atom({
  key: `stepState`,
  default: 0,
  dangerouslyAllowMutability: true,
})

export const biddingInfoState = atom({
  key: `biddingState`,
  default: {
    address: '',
    biddingDate: '',
    biddingDateString: '',
    biddingInfos: [
      {
        appraisalAmount: 0,
        bidDeposit: 0,
        biddingTime: '',
        minimumAmount: 0,
      },
    ],
    carInfo: '',
    caseDetail: '',
    caseNo: '',
    caseNoString: '',
    caseYear: '',
    courtFullName: '',
    dayDay: '',
    etcAddress: '',
    infoId: '',
    mulNo: '',
    mulSeq: '',
    reqCourtName: '',
    roadAddress: '',
    startDay: '',
    startMonth: '',
    startYear: '',
    usage: '',
    agent: {
      address: '',
      job: '',
      name: '',
      phoneNo: '',
      relationship: '',
      addressDetail: '',
      agentIdNum1: '',
      agentIdNum2: '',
      phoneNo1: '',
      phoneNo2: '',
      phoneNo3: '',
    },
    agentYn: '',
    bidDeposit: '',
    bidPrice: '',
    bidderCount: 0,
    bidders: [{
      peopleSeq: 0,
      bidderType: 'I',
      name: '',
      phoneNo: '',
      phoneNo1: '',
      phoneNo2: '',
      phoneNo3: '',
      idNum1: '',
      idNum2: '',
      address: '',
      addressDetail: '',
      job: '',
      companyNo: '',
      companyNo1: '',
      companyNo2: '',
      companyNo3: '',
      corporationNo: '',
      corporationNo1: '',
      corporationNo2: '',
      share: '',
      mandateYn: '',
    }],
    isFileCreated: false,
    selectedTime: '0',
    mstSeq: 0,
    state: 0,
    sagunNum: '',
    sagunAddr: '',
    ipchalDate: '',
    biddingInfo: {
      biddingTime: '',
      appraisalAmount: 0,
      minimumAmount: 0,
      bidDeposit: 0,
    },
    depositType: '',
    bidder: '',
    biddingPrice: 0,
    depositPrice: 0,
    pdfFile: new Blob(),
    idcode: '',
    aesUserId: '',
    imageFile: '',
    isModalOpen: false,
    shareWay: 'S',
    numerator: [''],
    denominator: [''],
    mandates: [
      {
        peopleSeq: 0,
        name: '',
        mandateYn: '',
      },
    ],
    pdfPassword: '',
    fileName: '',
    searchResults: [
      {
        infoId: '',
        caseNo: '',
        mulSeq: '',
        caseNoString: '',
        subCaseNoString: '',
        biddingDate: '',
        biddingDateString: '',
        usage: '',
        reqCourtName: '',
        mulNo: '',
        address: '',
        etcAddress: '',
        roadAddress: '',
        oldAddress: '',
        landArea: '',
        landPyungArea: '',
        buildingArea: '',
        buildingPyungArea: '',
        pyungHyung: '',
        failedBidsCount: '',
        checkInfo: '',
        biddingTime: '',
        bidderCount: '',
        nextLowestAmt: 0,
        carInfo: '',
        appraisalAmount: 0,
        minimumAmount: 0,
        rate: '',
      }
    ] || null,
    selectedCase: '',
    selectedYear: '',
    searchResultState: 1,
    tokenOk: false,
    isBiddingStatus: false,
  },
  dangerouslyAllowMutability: true,
})
