import EmotionProvider from '@/components/layout/EmotionProvider'
import ReactQueryProviders from '@/hooks/useReactQuery'
import { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProviders>
          <EmotionProvider>
            {children}
          </EmotionProvider>
        </ReactQueryProviders>
      </body>
    </html>
  )
}
